version: '3.8'

services:
  data-formulator:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=py-src/data_formulator/app.py
      - FLASK_RUN_PORT=5000
      - FLASK_RUN_HOST=0.0.0.0
      # Add your API keys here as environment variables, e.g.:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - AZURE_API_KEY=${AZURE_API_KEY}
      - AZURE_API_BASE=${AZURE_API_BASE}
      - AZURE_API_VERSION=${AZURE_API_VERSION}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - OLLAMA_API_BASE=${OLLAMA_API_BASE}
    volumes:
      - .:/app # Mount the current directory for development