# Dockerfile for React frontend (Vite)
FROM node:20-alpine as build
WORKDIR /app
COPY package.json package-lock.json* yarn.lock* ./
RUN npm install
COPY src ./src
COPY public ./public
COPY index.html ./
COPY tsconfig.json ./
COPY vite.config.ts ./
RUN npm run build

FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
# Đổi port nginx sang 8001
RUN sed -i 's/listen       80;/listen       8001;/g' /etc/nginx/conf.d/default.conf
EXPOSE 8001
CMD ["nginx", "-g", "daemon off;"]
