"""Unit tests for the :func:`get_credential_vault` factory function.

Verifies:
- CREDENTIAL_VAULT_KEY env var → uses explicit key
- No env var → auto-generates key file in data home
- Existing .vault_key file → reuses it
- CREDENTIAL_VAULT=unknown → returns None
- Singleton behaviour (multiple calls return same instance)
"""
from __future__ import annotations

from pathlib import Path

import pytest
from cryptography.fernet import Fernet

pytestmark = [pytest.mark.backend, pytest.mark.vault]


@pytest.fixture(autouse=True)
def _reset_vault_singleton():
    """Reset module-level singleton state between tests."""
    import data_formulator.auth.vault as vault_mod
    vault_mod._vault = None
    vault_mod._initialized = False
    yield
    vault_mod._vault = None
    vault_mod._initialized = False


class TestExplicitKey:

    def test_env_key_takes_priority(self, tmp_path, monkeypatch):
        key = Fernet.generate_key().decode()
        monkeypatch.setenv("CREDENTIAL_VAULT_KEY", key)
        monkeypatch.setenv("CREDENTIAL_VAULT", "local")
        monkeypatch.setattr(
            "data_formulator.auth.vault.get_data_formulator_home",
            lambda: tmp_path,
        )

        from data_formulator.auth.vault import get_credential_vault
        from data_formulator.auth.vault.local_vault import LocalCredentialVault

        vault = get_credential_vault()
        assert isinstance(vault, LocalCredentialVault)
        # Should NOT create .vault_key file when env var is set
        assert not (tmp_path / ".vault_key").exists()

    def test_default_type_is_local(self, tmp_path, monkeypatch):
        key = Fernet.generate_key().decode()
        monkeypatch.setenv("CREDENTIAL_VAULT_KEY", key)
        monkeypatch.delenv("CREDENTIAL_VAULT", raising=False)
        monkeypatch.setattr(
            "data_formulator.auth.vault.get_data_formulator_home",
            lambda: tmp_path,
        )

        from data_formulator.auth.vault import get_credential_vault
        from data_formulator.auth.vault.local_vault import LocalCredentialVault

        vault = get_credential_vault()
        assert isinstance(vault, LocalCredentialVault)


class TestAutoGeneratedKey:

    def test_auto_generates_key_when_no_env(self, tmp_path, monkeypatch):
        """No env var → auto-generate .vault_key and return a working vault."""
        monkeypatch.delenv("CREDENTIAL_VAULT_KEY", raising=False)
        monkeypatch.delenv("CREDENTIAL_VAULT", raising=False)
        monkeypatch.setattr(
            "data_formulator.auth.vault.get_data_formulator_home",
            lambda: tmp_path,
        )

        from data_formulator.auth.vault import get_credential_vault
        from data_formulator.auth.vault.local_vault import LocalCredentialVault

        vault = get_credential_vault()
        assert isinstance(vault, LocalCredentialVault)

        key_file = tmp_path / ".vault_key"
        assert key_file.exists()
        key_content = key_file.read_text(encoding="utf-8").strip()
        assert len(key_content) > 0
        # Verify it's a valid Fernet key
        Fernet(key_content.encode())

    def test_reuses_existing_key_file(self, tmp_path, monkeypatch):
        """Existing .vault_key file → reuse, don't overwrite."""
        existing_key = Fernet.generate_key().decode()
        key_file = tmp_path / ".vault_key"
        key_file.write_text(existing_key + "\n", encoding="utf-8")

        monkeypatch.delenv("CREDENTIAL_VAULT_KEY", raising=False)
        monkeypatch.setattr(
            "data_formulator.auth.vault.get_data_formulator_home",
            lambda: tmp_path,
        )

        from data_formulator.auth.vault import get_credential_vault
        from data_formulator.auth.vault.local_vault import LocalCredentialVault

        vault = get_credential_vault()
        assert isinstance(vault, LocalCredentialVault)
        # Key file should still contain the same key
        assert key_file.read_text(encoding="utf-8").strip() == existing_key

    def test_auto_generated_vault_is_functional(self, tmp_path, monkeypatch):
        """Auto-generated vault can actually store and retrieve credentials."""
        monkeypatch.delenv("CREDENTIAL_VAULT_KEY", raising=False)
        monkeypatch.setattr(
            "data_formulator.auth.vault.get_data_formulator_home",
            lambda: tmp_path,
        )

        from data_formulator.auth.vault import get_credential_vault

        vault = get_credential_vault()
        vault.store("user:alice", "superset", {"password": "s3cret"})
        assert vault.retrieve("user:alice", "superset") == {"password": "s3cret"}


class TestFactoryReturnsNone:

    def test_unknown_type_returns_none(self, tmp_path, monkeypatch):
        key = Fernet.generate_key().decode()
        monkeypatch.setenv("CREDENTIAL_VAULT_KEY", key)
        monkeypatch.setenv("CREDENTIAL_VAULT", "hashicorp")
        monkeypatch.setattr(
            "data_formulator.auth.vault.get_data_formulator_home",
            lambda: tmp_path,
        )

        from data_formulator.auth.vault import get_credential_vault

        assert get_credential_vault() is None


class TestSingleton:

    def test_multiple_calls_return_same_instance(self, tmp_path, monkeypatch):
        key = Fernet.generate_key().decode()
        monkeypatch.setenv("CREDENTIAL_VAULT_KEY", key)
        monkeypatch.setattr(
            "data_formulator.auth.vault.get_data_formulator_home",
            lambda: tmp_path,
        )

        from data_formulator.auth.vault import get_credential_vault

        v1 = get_credential_vault()
        v2 = get_credential_vault()
        assert v1 is v2

    def test_singleton_is_cached(self, tmp_path, monkeypatch):
        monkeypatch.delenv("CREDENTIAL_VAULT_KEY", raising=False)
        monkeypatch.setattr(
            "data_formulator.auth.vault.get_data_formulator_home",
            lambda: tmp_path,
        )

        from data_formulator.auth.vault import get_credential_vault
        import data_formulator.auth.vault as vault_mod

        v1 = get_credential_vault()
        assert vault_mod._initialized is True
        v2 = get_credential_vault()
        assert v1 is v2
