# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

"""Base class for plugin authentication with built-in Credential Vault lifecycle.

Plugin authors subclass :class:`PluginAuthHandler` and implement four methods:

* ``do_login(username, password)`` — authenticate with the external system
* ``do_clear_session()`` — clear Flask session keys for this plugin
* ``get_session_auth()`` — check if the current session is authenticated
* ``get_current_user()`` — return the current user dict from session

The base class enforces:

* **Vault store/delete** — encrypted credential storage, keyed by identity
* **Three-mode auth negotiation** — Session → Vault auto-login → Manual
* **Logout cleanup** — always clears both Session *and* Vault
* **Standard route generation** — ``/login``, ``/logout``, ``/status``, ``/me``

Usage::

    class MyAuthHandler(PluginAuthHandler):
        def do_login(self, username, password):
            ...
        def do_clear_session(self):
            ...
        def get_session_auth(self):
            ...
        def get_current_user(self):
            ...

    _handler = MyAuthHandler("my_plugin")
    auth_bp = _handler.create_auth_blueprint("/api/plugins/my_plugin/auth")

    # Add plugin-specific routes to auth_bp if needed
    @auth_bp.route("/custom", methods=["POST"])
    def custom_route(): ...
"""
from __future__ import annotations

import logging
from abc import ABC, abstractmethod
from typing import Any, Optional

from flask import Blueprint, jsonify, request

from data_formulator.security.sanitize import sanitize_error_message

logger = logging.getLogger(__name__)


class PluginAuthHandler(ABC):
    """Base class for plugin auth with built-in Vault lifecycle.

    Standard routes (login, logout, status, me) are generated by
    :meth:`create_auth_blueprint`.  Vault store / delete / auto-login
    is handled automatically — plugin authors cannot forget it.
    """

    def __init__(self, plugin_id: str):
        self.plugin_id = plugin_id

    # ------------------------------------------------------------------
    # Abstract: plugin author implements these
    # ------------------------------------------------------------------

    @abstractmethod
    def do_login(self, username: str, password: str) -> dict[str, Any]:
        """Authenticate with the external system and save to Flask session.

        Must call the external system's login API, persist the resulting
        token / user in the Flask session, and return user info.

        Returns::

            {"user": {"id": ..., "username": ..., "first_name": ..., "last_name": ...}}

        Raises:
            Exception on authentication failure.
        """
        ...

    @abstractmethod
    def do_clear_session(self) -> None:
        """Clear all plugin-specific keys from the Flask session."""
        ...

    @abstractmethod
    def get_session_auth(self) -> Optional[dict[str, Any]]:
        """Check the Flask session for existing authentication.

        Returns a status dict if authenticated::

            {"authenticated": True, "mode": "session", "user": {...}}

        Returns ``None`` if no valid session exists.
        """
        ...

    @abstractmethod
    def get_current_user(self) -> Optional[dict[str, Any]]:
        """Return the current user dict from the session, or ``None``."""
        ...

    # ------------------------------------------------------------------
    # Vault helpers — built-in, plugin authors should not override
    # ------------------------------------------------------------------

    def _get_vault(self):
        from data_formulator.credential_vault import get_credential_vault
        return get_credential_vault()

    def _get_identity(self) -> str:
        from data_formulator.security.auth import get_identity_id
        return get_identity_id()

    def vault_store(self, credentials: dict) -> None:
        """Store credentials in the Vault (best-effort, never raises)."""
        vault = self._get_vault()
        if not vault:
            return
        try:
            vault.store(self._get_identity(), self.plugin_id, credentials)
        except Exception:
            logger.warning("Failed to store credentials in vault for %s", self.plugin_id, exc_info=True)

    def vault_delete(self) -> None:
        """Delete credentials from the Vault (best-effort, never raises)."""
        vault = self._get_vault()
        if not vault:
            return
        try:
            vault.delete(self._get_identity(), self.plugin_id)
        except Exception:
            logger.warning("Failed to delete credentials from vault for %s", self.plugin_id, exc_info=True)

    def vault_retrieve(self) -> Optional[dict]:
        """Retrieve credentials from the Vault, or ``None``."""
        vault = self._get_vault()
        if not vault:
            return None
        try:
            return vault.retrieve(self._get_identity(), self.plugin_id)
        except Exception:
            logger.warning("Failed to retrieve credentials from vault for %s", self.plugin_id, exc_info=True)
            return None

    def try_vault_login(self) -> Optional[dict[str, Any]]:
        """Attempt auto-login with Vault credentials.

        Returns ``None`` if no Vault or no stored credentials.
        Otherwise returns a status dict (success or vault_stale).
        """
        stored = self.vault_retrieve()
        if not stored:
            return None

        username = stored.get("username", "")
        password = stored.get("password", "")
        if not username or not password:
            return None

        try:
            result = self.do_login(username, password)
            return {
                "status": "ok",
                "authenticated": True,
                "mode": "vault",
                "user": result["user"],
            }
        except Exception as exc:
            logger.info("Vault credentials stale for %s: %s", self.plugin_id, exc)
            return {
                "status": "ok",
                "authenticated": False,
                "vault_stale": True,
            }

    # ------------------------------------------------------------------
    # Blueprint factory
    # ------------------------------------------------------------------

    def create_auth_blueprint(self, url_prefix: str) -> Blueprint:
        """Create a Flask Blueprint with standard auth routes.

        Generated routes:

        - ``POST /login``   — authenticate + Vault store/delete
        - ``POST /logout``  — clear session + Vault delete (enforced)
        - ``GET  /status``  — three-mode negotiation
        - ``GET  /me``      — current user

        Returns the Blueprint so plugin-specific routes can be added::

            auth_bp = handler.create_auth_blueprint(prefix)
            @auth_bp.route("/my-custom-route", methods=["POST"])
            def custom(): ...
        """
        bp_name = f"plugin_{self.plugin_id}_auth"
        bp = Blueprint(bp_name, self.__class__.__module__, url_prefix=url_prefix)
        handler = self

        @bp.route("/login", methods=["POST"])
        def login():
            data = request.get_json(force=True)
            username = data.get("username", "")
            password = data.get("password", "")
            remember = data.get("remember", False)

            if not username or not password:
                return jsonify({"status": "error", "message": "Missing credentials"}), 400

            try:
                result = handler.do_login(username, password)
            except Exception as exc:
                logger.warning("Login failed for %s: %s", username, exc)
                return jsonify({"status": "error", "message": sanitize_error_message(str(exc))}), 401

            if remember:
                handler.vault_store({"username": username, "password": password})
            else:
                handler.vault_delete()

            return jsonify({"status": "ok", **result})

        @bp.route("/logout", methods=["POST"])
        def logout():
            handler.do_clear_session()
            handler.vault_delete()
            return jsonify({"status": "ok"})

        @bp.route("/status", methods=["GET"])
        def auth_status():
            session_result = handler.get_session_auth()
            if session_result is not None:
                return jsonify({"status": "ok", **session_result})

            vault_result = handler.try_vault_login()
            if vault_result is not None:
                return jsonify(vault_result)

            return jsonify({"status": "ok", "authenticated": False})

        @bp.route("/me", methods=["GET"])
        def me():
            user = handler.get_current_user()
            if not user:
                return jsonify({"status": "error", "message": "Not authenticated"}), 401
            return jsonify({"status": "ok", "user": user})

        return bp
